### PR TITLE
🌱 primitives/layout: layout can receive reverse as direction

### PR DESCRIPTION
**Pull request by DonGideon**
just an idea, currently it can be very useful for me in case like:

we want to have:
icon - spacer - text
but also:
text - spacer - icon

WDYT?

Screenshot 2020-01-10 at 17 31 05

### CODE REVIEW

**Comment by DonGideon** [comment]
@deepsweet @xaviervia would love your opinion 🙌

**Comment by deepsweet** [comment]
I'd say that it's better to avoid such CSS magic. For example I'm not sure how does it work when it comes to a11y tab-order: it looks totally different from actual DOM and visual perspective.

**Comment by xaviervia** [comment]
Let's avoid adding flex options that can be achieved by other ways

**Comment by DonGideon** [comment]
@deepsweet @xaviervia thanks! agree!

**Pull request closed without merging**
