### PR TITLE
🐞 sandbox/ui: expose more sandbox ui components

### PR DESCRIPTION
**Pull request by xaviervia**

### CODE REVIEW

**Comment by deepsweet** [comment]
but why? that's all an internal implementation, Sandbox UI is React app, not component library.

**Comment by xaviervia** [comment]
@deepsweet some were missing from being reexported, `switch` for example. I tried to use them and then realized they were not made available.

Then I went bananas and exported them all just in case, because I'm not sure which are necessary and which are not. I'm not certain on how to know. Should I just expose the ones I know I need?

**Comment by deepsweet** [comment]
I'd say we should expose none of them at all — that's just a huge API contract we'll have to support. If we manage to refactor everything using `revert` then 90% of "re-exported" components will just disappear, forcing us to publish a breaking change we could avoid.

**Comment by xaviervia** [comment]
Hm, makes sense to pull it from `revert` instead.

I think the breaking change will be necessary anyway because we are already exposing many components that will be in `revert` in the future. But we can skip this PR and wait for `revert` instead.

**Comment by deepsweet** [comment]
expose only what you need so far then

**Comment by xaviervia** [comment]
switch is what I need, I'll expose that one. I'll push in a couple of hours

**Pull request merged**
